package org.javacrafters.core;
//Button Type
public enum BT {
    //MAIN BUTTONS
    GET_INFO,
    SETTINGS,
    TO_MAIN,
    TO_SETTINGS,
    //SETTING BUTTONS
    DECIMAL_PLACES,
    BANK,
    CURRENCIES,
    NOTIFICATION_TIME,
    //DECIMAL BUTTONS
    TWO_DIGITS,
    THREE_DIGITS,
    FOUR_DIGITS,
    //CURRENCIES BUTTONS
    USD,
    EUR,
    //BANK BUTTONS
    NBU,
    MONO,
    PRIVAT,
    //NOTIFY TIME BUTTONS
    NINE_O_CLOCK,
    TEN_O_CLOCK,
    ELEVEN_O_CLOCK,
    TWELVE_O_CLOCK,
    THIRTEEN_O_CLOCK,
    FOURTEEN_O_CLOCK,
    FIFTEEN_O_CLOCK,
    SIXTEEN_O_CLOCK,
    SEVENTEEN_O_CLOCK,
    EIGHTEEN_O_CLOCK
}

